import { PropsWithChildren } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import {cn} from 'common/helpers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-gray-100 h-[100dvh]')}>{children}</body>
    </html>
  )
}

export default RootLayout
